[package]
name = "font_helper"
version = "0.1.5"
authors = ["Chugunov Roman <Zebs-BMK@yandex.ru>"]
edition = "2018"
license = "GPL-2.0-only"
description = "Font Helper for Figma for Linux platform"
homepage = "https://github.com/ChugunovRoman/figma-linux-font-helper"
repository = "https://github.com/ChugunovRoman/figma-linux-font-helper"

[dependencies]
libfonthelper = "0.2.8"
simple-server = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flexi_logger = "0.14.3"
log = "0.4.8"
percent-encoding = "2.1.0"
